OFFICE_FOOTBALL_POOL_URL = 'https://www.officefootballpool.com'
FOOTBALL_POOL_ID = 61547
PICKS_PAGE = 'picks.cfm'
LOGIN_PAGE = 'members.cfm'
USER_AGENT = {
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36'}

TEAM_MAPPER = {
    'la rams': ['Los Angeles Rams', 'ram'],
    'buffalo': ['Buffalo Bills', 'buf'],
    'atlanta': ['Atlanta Falcons', 'atl'],
    'new orleans': ['New Orleans Saints', 'nor'],
    'chicago': ['Chicago Bears', 'chi'],
    'cincinnati': ['Cincinnati Bengals', 'cin'],
    'detroit': ['Detroit Lions', 'det'],
    'miami': ['Miami Dolphins', 'mia'],
    'ny jets': ['New York Jets', 'nyj'],
    'washington': ['Washington Redskins', 'was'],
    'carolina': ['Carolina Panthers', 'car'],
    'houston': ['Houston Texans', 'htx'],
    'tennessee': ['Tennessee Titans', 'oti'],
    'minnesota': ['Minnesota Vikings', 'min'],
    'arizona': ['Arizona Cardinals', 'crd'],
    'la chargers': ['Los Angeles Chargers', 'sdg'],
    'dallas': ['Dallas Cowboys', 'dal'],
    'seattle': ['Seattle Seahawks', 'sea'],
    'san francisco': ['San Francisco 49ers', 'sfo'],
    'pittsburgh': ['Pittsburgh Steelers', 'pit'],
    'philadelphia': ['Philadelphia Eagles', 'phi'],
    'new england': ['New England Patriots', 'nwe'],
    'baltimore': ['Baltimore Ravens', 'rav'],
    'jacksonville': ['Jacksonville Jaguars', 'jax'],
    'cleveland': ['Cleveland Browns', 'cle'],
    'indianapolis': ['Indianapolis Colts', 'clt'],
    'ny giants': ['New York Giants', 'nyg'],
    'green bay': ['Green Bay Packers', 'gnb'],
    'kansas city': ['Kansas City Chiefs', 'kan'],
    'las vegas': ['Las Vegas Raiders', 'rai'],
    'tampa bay': ['Tampa Bay Buccaneers', 'tam'],
    'denver': ['Denver Broncos', 'den'],
}

PLACE_HOLDERS = {
    'boxscore_text': '',
    'result': '',
    'OT': '',
    'record': '',
    'team_score': '',
    'opp_score': '',
    'off_first_downs': '',
    'off_total_yds': '',
    'off_pass_yds': '',
    'off_rush_yds': '',
    'off_turn_overs': '',
    'def_first_downs': '',
    'def_total_yds': '',
    'def_pass_yds': '',
    'def_rush_yds': '',
    'def_turn_overs': '',
    'off_exp_pts': '',
    'def_exp_pts': '',
    'specialTm_exp_pts': '',
    'Won_Toss': '',
    'Roof': '',
    'Surface': '',
    'Vegas_Line_Close': '',
    'O/U_Line': '',
    'O/U_Result': '',
    'aFirst_Downs': '',
    'hFirst_Downs': '',
    'aRush-Yds-Tds': '0-0-0',
    'hRush-Yds-Tds': '0-0-0',
    'aCmp-Att-Yd-TD-INT': '0-0-0-0-0',
    'hCmp-Att-Yd-TD-INT': '0-0-0-0-0',
    'aSacked-Yds': '',
    'hSacked-Yds': '',
    'aNet_Pass_Yds': '',
    'hNet_Pass_Yds': '',
    'aTotal_Yds': '',
    'h_Total_Yds': '',
    'aFumbles-Lost': '',
    'hFumbles-Lost': '',
    'aTurnovers': '',
    'hTurnovers': '',
    'aPenalties-Yds': '0-0',
    'h-Penalties-Yds': '0-0',
    'aThird_Down_Conv': '0-0',
    'hThird_Down_Conv': '0-0',
    'aFourth_Down_Conv': '0-0',
    'hFourth_Down_Conv': '0-0',
    'aTime_of_Possesion': '',
    'hTime_of_Possesion': '',
}
