OFFICE_FOOTBALL_POOL_URL = 'https://www.officefootballpool.com'
FOOTBALL_POOL_ID = 61547
PICKS_PAGE = 'picks.cfm'
LOGIN_PAGE = 'members.cfm'
USER_AGENT = {
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36'
}

MASTER_PATH = './nfl_master_2012-2022.csv'
GAME_SPAN = 10
START_YEAR = 2012
# Used in build_dataset.py to uniquely identify a franchise, regardless of name/city change
FRANCHISES = [
    'Arizona Cardinals',
    'Atlanta Falcons',
    'Baltimore Ravens',
    'Buffalo Bills',
    'Carolina Panthers',
    'Chicago Bears',
    'Cincinnati Bengals',
    'Cleveland Browns',
    'Dallas Cowboys',
    'Denver Broncos',
    'Detroit Lions',
    'Green Bay Packers',
    'Houston Texans',
    'Indianapolis Colts',
    'Jacksonville Jaguars',
    'Kansas City Chiefs',
    'Miami Dolphins',
    'Minnesota Vikings',
    'New England Patriots',
    'New Orleans Saints',
    'New York Giants',
    'New York Jets',
    'Oakland Raiders',
    'Philadelphia Eagles',
    'Pittsburgh Steelers',
    'San Diego Chargers',
    'San Francisco 49ers',
    'Seattle Seahawks',
    'St. Louis Rams',
    'Tampa Bay Buccaneers',
    'Tennessee Titans',
    'Washington Redskins',
]

TEAM_MAPPER = {
    'la rams': ['Los Angeles Rams', 'ram'],
    'buffalo': ['Buffalo Bills', 'buf'],
    'atlanta': ['Atlanta Falcons', 'atl'],
    'new orleans': ['New Orleans Saints', 'nor'],
    'chicago': ['Chicago Bears', 'chi'],
    'cincinnati': ['Cincinnati Bengals', 'cin'],
    'detroit': ['Detroit Lions', 'det'],
    'miami': ['Miami Dolphins', 'mia'],
    'ny jets': ['New York Jets', 'nyj'],
    'washington': ['Washington Redskins', 'was'],
    'carolina': ['Carolina Panthers', 'car'],
    'houston': ['Houston Texans', 'htx'],
    'tennessee': ['Tennessee Titans', 'oti'],
    'minnesota': ['Minnesota Vikings', 'min'],
    'arizona': ['Arizona Cardinals', 'crd'],
    'la chargers': ['Los Angeles Chargers', 'sdg'],
    'dallas': ['Dallas Cowboys', 'dal'],
    'seattle': ['Seattle Seahawks', 'sea'],
    'san francisco': ['San Francisco 49ers', 'sfo'],
    'pittsburgh': ['Pittsburgh Steelers', 'pit'],
    'philadelphia': ['Philadelphia Eagles', 'phi'],
    'new england': ['New England Patriots', 'nwe'],
    'baltimore': ['Baltimore Ravens', 'rav'],
    'jacksonville': ['Jacksonville Jaguars', 'jax'],
    'cleveland': ['Cleveland Browns', 'cle'],
    'indianapolis': ['Indianapolis Colts', 'clt'],
    'ny giants': ['New York Giants', 'nyg'],
    'green bay': ['Green Bay Packers', 'gnb'],
    'kansas city': ['Kansas City Chiefs', 'kan'],
    'las vegas': ['Las Vegas Raiders', 'rai'],
    'tampa bay': ['Tampa Bay Buccaneers', 'tam'],
    'denver': ['Denver Broncos', 'den'],
}

# Used in cleaner.py
OPPONENT_ABBREV_MAP = {
    'crd': ['Arizona Cardinals'],
    'atl': ['Atlanta Falcons'],
    'rav': ['Baltimore Ravens'],
    'buf': ['Buffalo Bills'],
    'car': ['Carolina Panthers'],
    'chi': ['Chicago Bears'],
    'cin': ['Cincinnati Bengals'],
    'cle': ['Cleveland Browns'],
    'dal': ['Dallas Cowboys'],
    'den': ['Denver Broncos'],
    'det': ['Detroit Lions'],
    'gnb': ['Green Bay Packers'],
    'htx': ['Houston Texans'],
    'clt': ['Indianapolis Colts'],
    'jax': ['Jacksonville Jaguars'],
    'kan': ['Kansas City Chiefs'],
    'mia': ['Miami Dolphins'],
    'min': ['Minnesota Vikings'],
    'nwe': ['New England Patriots'],
    'nor': ['New Orleans Saints'],
    'nyg': ['New York Giants'],
    'nyj': ['New York Jets'],
    'rai': ['Oakland Raiders', 'Las Vegas Raiders'],
    'phi': ['Philadelphia Eagles'],
    'pit': ['Pittsburgh Steelers'],
    'sdg': ['San Diego Chargers', 'Los Angeles Chargers'],
    'sfo': ['San Francisco 49ers'],
    'sea': ['Seattle Seahawks'],
    'ram': ['St. Louis Rams', 'Los Angeles Rams'],
    'tam': ['Tampa Bay Buccaneers'],
    'oti': ['Tennessee Titans'],
    'was': ['Washington Redskins', 'Washington Football Team', 'Washington Commanders']
}

# Used in build_dataset.py
FRANCHISE_ABBRV = list(OPPONENT_ABBREV_MAP.keys())

# Used by build_dataset.py and pfr_scraper.py
SHARED_COLS = [
    'result',
    'OT',
    'record',
    'at',
    'opponent',
    'team_score',
    'opp_score',
    'off_first_downs',
    'off_total_yds',
    'off_pass_yds',
    'off_rush_yds',
    'off_turn_overs',
    'def_first_downs',
    'def_total_yds',
    'def_pass_yds',
    'def_rush_yds',
    'def_turn_overs',
    'off_exp_pts',
    'def_exp_pts',
    'specialTm_exp_pts',
    'Won_Toss',
    'Roof',
    'Surface',
    'Vegas_Line_Close',
    'O/U_Line',
    'O/U_Result',
    'aFirst_Downs',
    'hFirst_Downs',
    'aRush-Yds-Tds',
    'hRush-Yds-Tds',
    'aCmp-Att-Yd-TD-INT',
    'hCmp-Att-Yd-TD-INT',
    'aSacked-Yds',
    'hSacked-Yds',
    'aNet_Pass_Yds',
    'hNet_Pass_Yds',
    'aTotal_Yds',
    'h_Total_Yds',
    'aFumbles-Lost',
    'hFumbles-Lost',
    'aTurnovers',
    'hTurnovers',
    'aPenalties-Yds',
    'h-Penalties-Yds',
    'aThird_Down_Conv',
    'hThird_Down_Conv',
    'aFourth_Down_Conv',
    'hFourth_Down_Conv',
    'aTime_of_Possesion',
    'hTime_of_Possesion',
]

# These are only valid for years >= 2012
ADDITIONAL_COLS = [
    'hOff_snap_count',
    'hDef_snap_count',
    'hST_snap_count',
    'aOff_snap_count',
    'aDef_snap_count',
    'aST_snap_count',
    'hDef_int',
    'hDef_int_yds',
    'hDef_int_td',
    'hDef_int_long',
    'hPass_defended',
    'hSacks',
    'hTackles_combined',
    'hTackles_solo',
    'hTackles_assists',
    'hTackles_loss',
    'hQb_hits',
    'hFumbles_rec',
    'hFumbles_rec_yds',
    'hFumbles_rec_td',
    'hFumbles_forced',
    'aDef_int',
    'aDef_int_yds',
    'aDef_int_td',
    'aDef_int_long',
    'aPass_defended',
    'aSacks',
    'aTackles_combined',
    'aTackles_solo',
    'aTackles_assists',
    'aTackles_loss',
    'aQb_hits',
    'aFumbles_rec',
    'aFumbles_rec_yds',
    'aFumbles_rec_td',
    'aFumbles_forced',
]

PLACE_HOLDERS = {
    'boxscore_text': '',
    'result': '',
    'OT': '',
    'record': '',
    'team_score': '',
    'opp_score': '',
    'off_first_downs': '',
    'off_total_yds': '',
    'off_pass_yds': '',
    'off_rush_yds': '',
    'off_turn_overs': '',
    'def_first_downs': '',
    'def_total_yds': '',
    'def_pass_yds': '',
    'def_rush_yds': '',
    'def_turn_overs': '',
    'off_exp_pts': '',
    'def_exp_pts': '',
    'specialTm_exp_pts': '',
    'Won_Toss': '',
    'Roof': '',
    'Surface': '',
    'Vegas_Line_Close': '',
    'O/U_Line': '',
    'O/U_Result': '',
    'aFirst_Downs': '',
    'hFirst_Downs': '',
    'aRush-Yds-Tds': '0-0-0',
    'hRush-Yds-Tds': '0-0-0',
    'aCmp-Att-Yd-TD-INT': '0-0-0-0-0',
    'hCmp-Att-Yd-TD-INT': '0-0-0-0-0',
    'aSacked-Yds': '',
    'hSacked-Yds': '',
    'aNet_Pass_Yds': '',
    'hNet_Pass_Yds': '',
    'aTotal_Yds': '',
    'h_Total_Yds': '',
    'aFumbles-Lost': '',
    'hFumbles-Lost': '',
    'aTurnovers': '',
    'hTurnovers': '',
    'aPenalties-Yds': '0-0',
    'h-Penalties-Yds': '0-0',
    'aThird_Down_Conv': '0-0',
    'hThird_Down_Conv': '0-0',
    'aFourth_Down_Conv': '0-0',
    'hFourth_Down_Conv': '0-0',
    'aTime_of_Possesion': '',
    'hTime_of_Possesion': '',
    'hOff_snap_count': '',
    'hDef_snap_count': '',
    'hST_snap_count': '',
    'aOff_snap_count': '',
    'aDef_snap_count': '',
    'aST_snap_count': '',
    'hDef_int': '',
    'hDef_int_yds': '',
    'hDef_int_td': '',
    'hDef_int_long': '',
    'hPass_defended': '',
    'hSacks': '',
    'hTackles_combined': '',
    'hTackles_solo': '',
    'hTackles_assists': '',
    'hTackles_loss': '',
    'hQb_hits': '',
    'hFumbles_rec': '',
    'hFumbles_rec_yds': '',
    'hFumbles_rec_td': '',
    'hFumbles_forced': '',
    'aDef_int': '',
    'aDef_int_yds': '',
    'aDef_int_td': '',
    'aDef_int_long': '',
    'aPass_defended': '',
    'aSacks': '',
    'aTackles_combined': '',
    'aTackles_solo': '',
    'aTackles_assists': '',
    'aTackles_loss': '',
    'aQb_hits': '',
    'aFumbles_rec': '',
    'aFumbles_rec_yds': '',
    'aFumbles_rec_td': '',
    'aFumbles_forced': '',
}
