name: nfl_py3
channels:
  - defaults
dependencies:
  - python=3.7
  - numpy
  - beautifulsoup4
  - html5lib
  - lxml
  - pandas
  - jupyter_core
  - pip
  - backports
  - python_abi
  - ipython
  - psutil
  - nest-asyncio
  - packaging
  - pywin32
  - libsodium
  - ucrt
  - python-dateutil
  - vc
  - decorator
  - debugpy
  - wheel
  - traitlets
  - backports.functools_lru_cache
  - pyzmq
  - jupyter_client
  - wcwidth
  - prompt-toolkit
  - pickleshare
  - backcall
  - matplotlib-inline
  - vs2015_runtime
  - pygments
  - setuptools
  - tornado
  - entrypoints
  - colorama
  - jedi
  - zeromq
  - six
  - pyparsing
  - parso
  - ipykernel
  - requests
  - bs4
  - cchardet
  - dtale
  - xgboost
  - tabulate
