#!/usr/bin/env bash
w() { printf '%s\n' "$2" > "$1.md"; }

# ---- Team HYG: bloat/hygiene mappers (read-only analysis + report) ----
w hyg-cli 'Audit src/nfl_ats/cli.py (5,549 lines) for shrinkage opportunities. Map: (1) commands that are dead or superseded (grep ROADMAP/docs for references before calling anything dead — label read vs inferred), (2) copy-pasted argument/parser blocks and their consolidation shape, (3) logic that belongs in library modules rather than the CLI layer, (4) error handling duplicated across commands. Do NOT edit code. Produce reports/wave1/hyg-cli.md with a table of concrete refactors, estimated line delta each, risk level, and which tests cover each region. End with a top-5 execution order.'
w hyg-experiment-runner 'Audit src/nfl_ats/experiment_runner.py (4,359 lines) for duplication and dead paths. Identify repeated bootstrap/scoring/record loops that could collapse into one parameterised core; flag any code path referencing retired docs (check docs/evaluator_power.md does not exist) or superseded registry formats. Do NOT edit. Report to reports/wave1/hyg-experiment-runner.md with per-refactor line deltas, risk, test coverage.'
w hyg-public-board 'Audit src/nfl_ats/public_board.py (4,101 lines) and src/nfl_ats/dashboard/findings_content.py (1,804 lines). These generate the public HTML site; find (1) inline HTML/CSS that duplicates theme tokens in src/nfl_ats/dashboard/theme.py, (2) repeated card/table renderers, (3) content strings that should live in data files. Do NOT edit. Report to reports/wave1/hyg-public-board.md with a dedup map and line-delta estimates. Note the UI/UX rubric at docs/uiux_rubric.md — flag anything blocking rubric dimension 6 (visual consistency).'
w hyg-cfb-cluster 'Audit the CFB cluster: src/nfl_ats/cfb.py (1,841), cfb_features.py (903), cross_league_transfer.py (891), plus any cfb* scripts under scripts/. Map shared helpers (schedule loading, team-code normalization, bootstrap plumbing) that re-implement src/nfl_ats utilities. Estimate consolidation line deltas. Do NOT edit. Report to reports/wave1/hyg-cfb-cluster.md.'
w hyg-market-cluster 'Audit src/nfl_ats/clv.py (2,243), rotation.py (1,356), estimation_variance.py (1,224), market_decomposition.py (1,376): duplicated bootstrap/blocking utilities, repeated provenance-writing blocks, dead exports. Cross-check against experiment_runner.py public API only via grep (do not deep-read it; another agent owns it). Do NOT edit. Report to reports/wave1/hyg-market-cluster.md.'
w hyg-player-cluster 'Audit src/nfl_ats/players.py (1,439), pick_refresh.py (1,061), best_pick_nomination.py (954): duplication, dead code, oversized functions (>60 lines), config constants scattered vs centralised. Do NOT edit. Report to reports/wave1/hyg-player-cluster.md with line deltas and risk.'
w hyg-scripts-audit 'scripts/ contains ~190 python files, many one-shot research screens sharing 30-60 lines of boilerplate each (schedule loading, argparse scaffolding, artifact writing, bootstrap helpers). Quantify the boilerplate: cluster scripts by shared-block similarity, estimate lines recoverable by extracting scripts/_common.py modules, list which 10 scripts are pure one-shot artifacts already recorded in the registry (candidates for archiving to an archive/ directory — do NOT delete). Report to reports/wave1/hyg-scripts-audit.md. This is the single biggest bloat surface; be thorough.'
w hyg-tests-audit 'tests/ is ~48,857 lines for a 67k-line src. Find: (1) near-duplicate test files differing only in fixture constants, (2) golden-value tests that pin implementation details rather than contracts, (3) dead fixtures/helpers in conftest files, (4) suites testing scripts scheduled for archival. NEVER recommend deleting contract, leakage, safety, or canary tests — those are release-blocking. Do NOT edit. Report to reports/wave1/hyg-tests-audit.md with per-cluster line deltas and a keep/merge/archive recommendation each.'
w hyg-docs-rot 'docs/ holds 154 markdown files plus HTML. Identify: stale docs contradicting ROADMAP.md/HANDOFF.md current state, duplicate topics, session-notes-style files that belong in a docs/archive/, broken relative links. Read docs/revisit_list.md first — several headline numbers there have no surviving evidence; list any doc citing missing artifacts. Do NOT delete or move anything. Report to reports/wave1/hyg-docs-rot.md as a triage table (keep / merge / archive / correct).'
w hyg-dead-code 'Sweep src/nfl_ats for dead exports: functions/classes never imported outside their own module and not referenced by any CLI command string, script, or test (grep-verify each candidate before listing; label each candidate measured when you verified zero references). Also find unused pyproject dependencies by mapping imports. Do NOT edit. Report to reports/wave1/hyg-dead-code.md with removal candidates and their reference-check evidence.'
w hyg-pyproject-infra 'Audit repo infrastructure for bloat and drift: pyproject.toml (deps unused/duplicated/missing groups), .github/workflows (CI gap: ruff format crashes locally on unreadable dirs but CI is fine — check if exclude of .promotion-* would help contributors), .gitignore completeness (session-ses_*.md pattern, .pytest_cache), Makefile/task runners if any, and whether uv lock groups match actual imports. Do NOT edit. Report to reports/wave1/hyg-pyproject-infra.md.'
w hyg-import-time-bombs 'On 2026-08-24 a class of bug was fixed: 19 screen scripts built DEFAULT_SCHEDULES from gitignored data/raw/* at import time, breaking CI test collection (commit c24799d). Verify the fix is complete: import every module under scripts/ in a fresh interpreter WITHOUT data present (simulate by checking no module-level code touches data/raw, data/processed, or artifacts/), list any remaining offenders with line numbers, and draft the exact patch for each. Do NOT apply patches. Also check src/nfl_ats/ for the same pattern. Report to reports/wave1/hyg-import-time-bombs.md.'

# ---- Team BLOG: backlog churn (plans + predeclaration drafts; NO window spending) ----
w blog-rwb12-drift 'ROADMAP item RWB-12 (Drift monitoring) is open. Read its row, docs/prospective_evidence.md, and the feature-family registry. Produce an implementation plan: what drift signals (feature distributions, missingness, probability calibration shift), where they hook into the weekly pipeline, storage format, alert thresholds, and the tests each piece needs. Write the plan to reports/wave1/blog-rwb12-drift.md AND implement the plan as code on your branch IF you can do so without touching evaluation semantics; gates must pass either way. You are NOT authorized to run any scoring look.'
w blog-rwb07-scorecards 'ROADMAP item RWB-07 (Season-level scorecards, in progress) needs completion. Read the row, existing scorecard code (grep scorecard), and docs/opener_evaluation.md. Produce: remaining-work list, then implement the missing pieces on your branch (accuracy/Brier/log-loss/ECE/CLV by season with intervals at both grades). No scoring looks against new data; reuse existing evaluation artifacts only. Gates must pass. Report to reports/wave1/blog-rwb07-scorecards.md.'
w blog-rwb09-experiment-registry 'ROADMAP item RWB-09 (Experiment registry, in progress). Read the row, registry/*.json structure, and nfl-ats experiment CLI. Identify gaps between what the registry claims and what artifacts exist (sample 10 entries, verify linked artifacts — label measured per entry). Implement fixes/gaps as code on your branch. No new experiments. Report to reports/wave1/blog-rwb09-experiment-registry.md.'
w blog-rwb18-weak-signal 'ROADMAP item RWB-18 (Weak-signal registry, in progress). Read the row, registry/weak_signals.json summary stats, and docs/revisit_list.md RESOLVED section. Task: make `nfl-ats weak-signals pool` and `status` output include per-family overlap warnings documented in HANDOFF, and verify all 107+ entries carry admissible classification values. Fix validator gaps as code. Do NOT reclassify anything yourself — reclassification requires re-running measurements, which you are NOT
